import "../styles/globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import cx from "classnames";
import style from "../styles/components/Mainlayout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body
        className={cx(
          inter.className,
          "grid",
          "grid-cols-2",
          "grid-rows-2",
          "grid-cols-[200px_auto]",
          "grid-rows-[64px_minmax(calc(100vh_-_64px_-_64px),_auto)_64px]",
          style.body
        )}
      >
        <header
          className={cx(
            style.header,
            "shadow-md",
            "flex",
            "items-center",
            "pl-4",
            "col-[1/3]"
          )}
        >
          Beyim
        </header>
        <nav
          className={cx(style.nav, "shadow-md", "col-[1_/_2]", "row-[2_/_3]")}
        >
          <ul className="flex gap-1 flex-col p-4 m-0">
            <li>
              <Link href="#">Colors</Link>
            </li>
            <li>
              <Link href="#">
                Typography
              </Link>
            </li>
            <li>
              <Link href="#">
                Checkbox
              </Link>
            </li>
            <li>
              <Link href="#">
               Status-Badge
              </Link>
            </li>
            <li>
              <Link href="#">
               Dropdown
              </Link>
            </li>
            <li>
              <Link href="#">
                Input
              </Link>
            </li>
            <li>
              <Link href="#">
                Colors
              </Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer
          className={cx(
            style.footer,
            "shadow-md",
            "col-[1/3]",
            "row-[3/4]",
            "pl-4",
            "flex",
            "items-center"
          )}
        >
          Beyim Tech © 2023
        </footer>
      </body>
    </html>
  );
}
